
const CUSTOMS_CATEGORIES = [
    // {
    //     "parentCategoryId": "0101",
    //     "subCategoryId": "90.10.10",
    //     "description": "Race horses, not for breeding",
    //     "ratePercentage": 40,
    //     "label": "Race Heese"
    // },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Pure- bred breeding animals",
        "subHeadingCode": "010121",
        "code": "0101210000",
        "description": "Pure- bred breeding animals",
        "gct": "15",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Other:",
        "subHeadingCode": "010129",
        "code": "0101291000",
        "description": "Race horses, not for breeding",
        "gct": "15",
        "importDuty": "5.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Other:",
        "subHeadingCode": "010129",
        "code": "0101299010",
        "description": "Horses not for breeding nesoi",
        "gct": "15",
        "importDuty": "5.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Other:",
        "subHeadingCode": "010129",
        "code": "0101299020",
        "description": "Other Horses for breeding nesoi",
        "gct": "15",
        "importDuty": "5.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Asses:",
        "subHeadingCode": "010130",
        "code": "0101301000",
        "description": "Pure- bred breeding animals",
        "gct": "15",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Asses:",
        "subHeadingCode": "010130",
        "code": "0101309010",
        "description": "Other asses for breeding",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Asses:",
        "subHeadingCode": "010130",
        "code": "0101309090",
        "description": "Other, nesoi",
        "gct": "15",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Other:",
        "subHeadingCode": "010190",
        "code": "0101900010",
        "description": "Mules and hinnies not for breeding nesoi",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live horses, asses, mules and hinnies.",
        "subChapterCode": "0101",
        "subHeading": "Other:",
        "subHeadingCode": "010190",
        "code": "0101900090",
        "description": "Mules and hinnies  for breeding nesoi",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Pure- bred breeding animals:",
        "subHeadingCode": "010221",
        "code": "0102211000",
        "description": "Bulls",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Pure- bred breeding animals:",
        "subHeadingCode": "010221",
        "code": "0102212000",
        "description": "Cows",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102291000",
        "description": "Bulls, for breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102292000",
        "description": "Bulls, for rearing, weighing not more than  270 kg",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102293000",
        "description": "Other bulls",
        "gct": "15",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102294000",
        "description": "Cows, for breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102295000",
        "description": "Cows, for rearing, weighing not more than  270 kg",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other:",
        "subHeadingCode": "010229",
        "code": "0102296000",
        "description": "Other cows",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Pure -bred  breeding animals",
        "subHeadingCode": "010231",
        "code": "0102310000",
        "description": "Pure -bred  breeding animals",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other",
        "subHeadingCode": "010239",
        "code": "0102390000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live bovine animals.",
        "subChapterCode": "0102",
        "subHeading": "Other",
        "subHeadingCode": "010290",
        "code": "0102900000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live swine.",
        "subChapterCode": "0103",
        "subHeading": "Pure-bred breeding animals",
        "subHeadingCode": "010310",
        "code": "0103100000",
        "description": "Pure-bred breeding animals",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live swine.",
        "subChapterCode": "0103",
        "subHeading": "Weighing less than 50 kg:",
        "subHeadingCode": "010391",
        "code": "0103911000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live swine.",
        "subChapterCode": "0103",
        "subHeading": "Weighing less than 50 kg:",
        "subHeadingCode": "010391",
        "code": "0103919000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live swine.",
        "subChapterCode": "0103",
        "subHeading": "Weighing 50 kg or more:",
        "subHeadingCode": "010392",
        "code": "0103921000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live swine.",
        "subChapterCode": "0103",
        "subHeading": "Weighing 50 kg or more:",
        "subHeadingCode": "010392",
        "code": "0103929000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Sheep:",
        "subHeadingCode": "010410",
        "code": "0104101000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Sheep:",
        "subHeadingCode": "010410",
        "code": "0104102000",
        "description": "For rearing",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Sheep:",
        "subHeadingCode": "010410",
        "code": "0104109000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Live animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Goats:",
        "subHeadingCode": "010420",
        "code": "0104201000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Goats:",
        "subHeadingCode": "010420",
        "code": "0104202000",
        "description": "For rearing",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live sheep and goats.",
        "subChapterCode": "0104",
        "subHeading": "Goats:",
        "subHeadingCode": "010420",
        "code": "0104209000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls.",
        "subChapterCode": "0105",
        "subHeading": "Fowls of the species Gallus domesticus:",
        "subHeadingCode": "010511",
        "code": "0105111000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls.",
        "subChapterCode": "0105",
        "subHeading": "Fowls of the species Gallus domesticus:",
        "subHeadingCode": "010511",
        "code": "0105112000",
        "description": "For rearing",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls.",
        "subChapterCode": "0105",
        "subHeading": "Fowls of the species Gallus domesticus:",
        "subHeadingCode": "010511",
        "code": "0105119000",
        "description": "Other",
        "gct": "16.50",
        "importDuty": "40.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    },
    {
        "chapter": "Dead animals",
        "chapterCode": "01",
        "subChapter": "Live poultry, that is to say, fowls of the species Gallus domesticus, ducks, geese, turkeys and guinea fowls.",
        "subChapterCode": "0105",
        "subHeading": "Turkeys:",
        "subHeadingCode": "010512",
        "code": "0105121000",
        "description": "For breeding",
        "gct": "16.50",
        "importDuty": "0.00",
        "scf": "-",
        "environmentalLevy": "0.50"
    }
];
export default CUSTOMS_CATEGORIES;
